version: '3'

services:
  rabbit:
    image: rabbitmq:management
    restart: always
    ports:
     - 5672:5672
     - 15672:15672
  flower:
    image: mher/flower
    restart: always
    command: flower --broker=pyamqp://guest@rabbit//
    ports:
     - 5555:5555
